sudo: false
language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
licenses:
    - android-sdk-license-5be876d5

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - ./gradlew assemble
    - android-wait-for-emulator

script:
  - adb logcat -c
  - ./gradlew connectedCheck --stacktrace

after_success:
  - mkdir ./app/build/reports/
  - mkdir ./app/build/reports/jacoco
  - mkdir ./app/build/reports/jacoco/test
  - mv ./app/build/outputs/reports/coverage/debug/report.xml ./app/build/reports/jacoco/test/jacocoTestReport.xml
  - ./gradlew coveralls --stacktrace

after_failure:
  - adb logcat -d E