language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
licenses:
    - android-sdk-license-5be876d5

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script:
  - gradle connectedCheck