language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
before_script:
    # Make sure the emulator has started before running tests
    - chmod +x gradlew
    - chmod +x wait_for_emulator
    - ./wait_for_emulator
script:
  - ./gradlew connectedCheck
